# -*- coding: utf-8 -*-
"""xor2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSidCOS8Ij8pkZD6uYvkvI2Iaii5mpBZ
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import  Dense
from tensorflow.keras import optimizers

# ADDED: Random seed so weight init will always be the same
tf.random.set_seed(69)

training_data = np.array([[0,0],[0,1],[1,0],[1,1]])
target_data = np.array([[0],[1],[1],[0]])

# Two inputs, two hidden units and 1 output
model = Sequential()
model.add(Dense(2, input_dim=2, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

# ADDED: Increased learning rate since we want this to overfit since input is fixed and allows for faster training.
sgd = optimizers.SGD(lr=0.1,  momentum=0.8)

# ADDED: Optimizer was set to a string instead of the optimizer variable above.
model.compile(loss='mean_squared_error', optimizer=sgd, metrics=['accuracy'])

# You will change number of epochs. You will want to use verbose=2 to see
# results for each epoch sometimes but it is very slow
#model.fit(training_data, target_data, epochs=200, verbose=2)
print("Xor Starting")

# ADDED: Kept this the same, no need to increase epochs since I increased the learning rate.
model.fit(training_data, target_data, epochs=200,verbose=2)

# ADDED: prints original output, rounded outputs, and weights
pred = model.predict(training_data)
print(f'\nPrediction unrounded:\n{pred}')
print(f'\nPrediction rounded:\n{pred.round()}')
print(f'\nWeights:\n{model.get_weights()}')



